# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
<<<<<<< Updated upstream
    labels:
      - "infra"
 - package-ecosystem: "gradle"
=======
  - package-ecosystem: "gradle"
>>>>>>> Stashed changes
    directories:
      - "/src/adservice"
    groups:
      gradle-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
<<<<<<< Updated upstream
=======
  - package-ecosystem: "pip"
    directories:
      - "/src/recommendationservice"
    groups:
      gradle-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"

>>>>>>> Stashed changes
