# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    groups:
      actions-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directories:
      - "/src/checkoutservice"
      - "/src/productcatalogservice"
    groups:
      go-production-dependencies:
        exclude-patterns:
          - "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
      - "/src/adservice"
    groups:
      gradle-production-dependencies:
        exclude-patterns:
          - "com.google.protobuf:protoc"
          - "io.grpc:protoc-gen-grpc-java"
          - "com.google.api.grpc:proto-google-common-protos"
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directories:
      - "/src/recommendationservice"
    groups:
      pip-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
