# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    groups:
      actions-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "**/Dockerfile"
    groups:
      docker-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directories:
      - "/src/checkoutservice"
      - "/src/productcatalogservice"
    groups:
      go-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
      - "/src/adservice"
    groups:
      gradle-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directories:
      - "/src/recommendationservice"
    groups:
      pip-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
