# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra"
 - package-ecosystem: "gradle"
    directories:
      - "/src/adservice"
    groups:
      gradle-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"
