# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  pull-requests: write
  contents: write
  packages: write
jobs:
  dependabot-auto-update-protobuf-diff:
    runs-on: ubuntu-latest
    # Only run this job if the PR is opened by dependabot and the last commit is from dependabot
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.head.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MY_TOKEN }}
      - name: Generate
        run: make clean docker-generate-protobuf
      - name: Commit only if there are changes
        run: |
          if ! git diff --quiet; then
            git config user.name "Charlie Le"
            git config user.email "charlie_le@apple.com"
            git add .
            git commit -s -m "chore: update protobuf"
            git push
          fi
