# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  actions: write
  pull-requests: write
  contents: write
  packages: write
jobs:
  dependabot-auto-update-protobuf-diff:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Generate
        run: make clean docker-generate-protobuf
      - name: Commit only if there are changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update protobuf"
            git push
#             Create a new branch for the commit
#            git checkout -b dependabot/protobuf
#            git push origin dependabot/protobuf
#
#            # Create a PR to the original branch
#            gh pr create --title "chore: update protobuf" --body "This PR updates the protobuf files" --base $GITHUB_HEAD_REF --head dependabot/protobuf
          fi
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
